[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 1_000
via_ir = false
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fuzz]
runs = 512

[invariant]
runs = 256
depth = 64
fail_on_revert = false
